apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-rbac-a
  namespace: rbac-a
subjects:
  - kind: ServiceAccount
    name: rbac-test-sa
    namespace: default
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-rbac-b
  namespace: rbac-b
subjects:
  - kind: ServiceAccount
    name: rbac-test-sa
    namespace: default
roleRef:
  kind: Role
  name: full-access-role
  apiGroup: rbac.authorization.k8s.io
