apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-test-sa
  namespace: default
  annotations:
    # AWS IRSA IAM Role ARN will be auto injected via Terraform variable
    eks.amazonaws.com/role-arn: ${IRSA_ROLE_ARN}
